language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy
script:
  # For speed up the CI process
  #   See: https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs
  - .ci-script/clippy_test.sh
  - cargo fmt -- --check && cargo build --all-features --all && cargo test --all-features --all
